### PR TITLE
Standardize request interceptor API

### PR DESCRIPTION
**Pull request by kettanaito**
> This pull request contains BREAKING CHANGES.

## Changes

- Uses `createInterceptor()` instead of the `RequestInterceptor` class:

```diff
-new RequestInterceptor(interceptors)
+createInterceptor({
+  modules: interceptors,
+  resolver(request) {}
+})
```

- Calling `createInterceptor` no longer enables the patching. Now you need to call `interceptor.apply()` to do that. 
- The `response` reference in the "response" event now has `response.headers` of a type `import('headers-utils').Headers` (previously Object).

## Motivation

Turn response interceptor into a basic unopinionated execution shell: accepts standard interceptor functions, initialized them, knows when to clean up.

### CODE REVIEW

**Comment by kettanaito** [comment]
Hi, gentlement, @marcosvega91, @msutkowski. May I please ask for your review on these changes?

I believe this is a foundation for the future support of `fetch` and other client-side interceptors.

**Review by marcosvega91 — APPROVED** [review]
This is a huge refactor but it sounds pretty good, nice :)

**Comment by praveenkeshri** [comment]
Hi @kettanaito 
The changes are still not present in the npm registry (https://www.npmjs.com/package/node-request-interceptor).

**Comment by kettanaito** [comment]
@praveenkeshri, the module has been migrated to `@mswjs/interceptors` (please see the README). This change, along with many others, has been published to that namespace.

**Pull request merged**
